webtalk_init -webtalk_dir /home/nicoq/Facu/Arquitectura/ArquitecturaDeComputadoras/TP3_BIPcorregido/TP3_BIP.sim/sim_1/behav/xsim/xsim.dir/tb_bip_BIP_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec  3 11:46:33 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2b011427-ecc6-49e8-8877-97b2ecdbe51e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e579c45705a04870b7c3f777f42b21a9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "106" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 19 Tara" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3497.604 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1150 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "129992_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3099380543 -regid "" -xml /home/nicoq/Facu/Arquitectura/ArquitecturaDeComputadoras/TP3_BIPcorregido/TP3_BIP.sim/sim_1/behav/xsim/xsim.dir/tb_bip_BIP_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/nicoq/Facu/Arquitectura/ArquitecturaDeComputadoras/TP3_BIPcorregido/TP3_BIP.sim/sim_1/behav/xsim/xsim.dir/tb_bip_BIP_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/nicoq/Facu/Arquitectura/ArquitecturaDeComputadoras/TP3_BIPcorregido/TP3_BIP.sim/sim_1/behav/xsim/xsim.dir/tb_bip_BIP_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
