# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.cache/wt [current_project]
set_property parent.project_path /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/gerac/.Xilinx/Vivado/2019.1/xhub/board_store} [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/new/memfile.mem
read_verilog -library xil_defaultlib {
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/new/MUX.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/new/PC.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/new/INCR.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/new/IF_ID.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/new/I_FETCH.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/new/INSTR_MEM.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/S_EXTEND.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/REG.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/CONTROL.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/ID_EX.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/I_DECODE.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/ALU.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/BOTTOM_MUX.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/ALU_CONTROL.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/EX_MEM.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/THREE_ONE_MUX.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/ALU_MUX.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/ADDER.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/I_EXECUTE.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/MEM_WB.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/AND_Gate.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/D_MEM.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/MEM.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/WB.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/FORWARDING_UNIT.v
  /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/PIPELINE.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top PIPELINE -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef PIPELINE.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file PIPELINE_utilization_synth.rpt -pb PIPELINE_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
