#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Nov 28 20:27:40 -03 2019
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim tb_bip_BIP_behav -key {Behavioral:sim_1:Functional:tb_bip_BIP} -tclbatch tb_bip_BIP.tcl -log simulate.log"
xsim tb_bip_BIP_behav -key {Behavioral:sim_1:Functional:tb_bip_BIP} -tclbatch tb_bip_BIP.tcl -log simulate.log

