# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-7482-cx-nice-evo-ii/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/new {
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/new/MUX.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/new/PC.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/new/INCR.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/new/IF_ID.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/new/I_FETCH.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/new/INSTR_MEM.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/S_EXTEND.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/REG.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/CONTROL.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/ID_EX.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/I_DECODE.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/ALU.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/BOTTOM_MUX.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/ALU_CONTROL.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/EX_MEM.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/THREE_ONE_MUX.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/ALU_MUX.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/ADDER.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/I_EXECUTE.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/MEM_WB.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/AND_Gate.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/D_MEM.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/MEM.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/WB.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/FORWARDING_UNIT.v
      /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.srcs/sources_1/imports/MIPS/PIPELINE.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top PIPELINE
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-7482-cx-nice-evo-ii/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
