webtalk_init -webtalk_dir /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.sim/sim_1/behav/xsim/xsim.dir/I_DECODE_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jul 28 17:11:14 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "206c7a62-cadd-4bd4-9f52-df8309f3af07" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e25cc01912a946c0a26cdad418b243aa" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "ManjaroLinux" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Manjaro Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-4100M CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2423.354 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "380 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.07_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "119272_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1960521717 -regid "" -xml /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.sim/sim_1/behav/xsim/xsim.dir/I_DECODE_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.sim/sim_1/behav/xsim/xsim.dir/I_DECODE_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/gerac/ArquitecturaDeComputadoras/TP4_MIPS/TP4_MIPS.sim/sim_1/behav/xsim/xsim.dir/I_DECODE_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
