#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Sep 18 03:58:10 -03 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto e2d8a3761b2c4b33be3beade74d66f7e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot PIPELINE_tb_behav xil_defaultlib.PIPELINE_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto e2d8a3761b2c4b33be3beade74d66f7e --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot PIPELINE_tb_behav xil_defaultlib.PIPELINE_tb xil_defaultlib.glbl -log elaborate.log

